// Loads the MySQL dump into Supabase.
// Usage: npm run seed [path-to-dump.sql] [--dry]
// Needs in .env: VITE_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY
import fs from 'node:fs';
import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const dry = process.argv.includes('--dry');
const file = process.argv.slice(2).find(a => !a.startsWith('--')) || 'C:/Users/DELL/Downloads/task_category.sql';
const url = process.env.VITE_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!dry && (!url || !key)) {
  console.error('Missing VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env');
  process.exit(1);
}
const supabase = dry ? null : createClient(url, key, { auth: { persistSession: false } });

const sql = fs.readFileSync(file, 'utf8');

// Parse one VALUES list of MySQL tuples into arrays of JS values.
function parseTuples(text) {
  const rows = [];
  let i = 0;
  const n = text.length;
  while (i < n) {
    while (i < n && text[i] !== '(') i++;
    if (i >= n) break;
    i++;
    const row = [];
    while (true) {
      while (text[i] === ' ' || text[i] === '\t') i++;
      if (text[i] === "'") {
        i++;
        let s = '';
        while (true) {
          const c = text[i];
          if (c === '\\') {
            const d = text[i + 1];
            const map = { n: '\n', r: '\r', t: '\t', 0: '\0', Z: '\x1a' };
            s += d in map ? map[d] : d;
            i += 2;
          } else if (c === "'") {
            if (text[i + 1] === "'") { s += "'"; i += 2; } else { i++; break; }
          } else { s += c; i++; }
        }
        row.push(s);
      } else {
        let j = i;
        while (text[j] !== ',' && text[j] !== ')') j++;
        const tok = text.slice(i, j).trim();
        row.push(tok.toUpperCase() === 'NULL' ? null : Number(tok));
        i = j;
      }
      if (text[i] === ',') { i++; continue; }
      if (text[i] === ')') { i++; break; }
    }
    rows.push(row);
  }
  return rows;
}

// Collect every INSERT statement per table.
const tables = {};
const re = /INSERT INTO `(\w+)` \(([^)]*)\) VALUES\s*([\s\S]*?);\s*\n/g;
let m;
while ((m = re.exec(sql))) {
  const cols = m[2].split(',').map(c => c.trim().replace(/`/g, ''));
  const t = (tables[m[1]] ||= { cols, rows: [] });
  t.rows.push(...parseTuples(m[3]));
}

const ZERO = /^0000-00-00/;
const clean = v => (typeof v === 'string' && ZERO.test(v) ? null : v);
const asDate = v => { v = clean(v); return typeof v === 'string' ? v.slice(0, 10) : v; };
const ts = v => { v = clean(v); return typeof v === 'string' ? v.replace(' ', 'T') + 'Z' : v; };

// dump rows -> array of objects keyed by column name
const objs = name => {
  const t = tables[name];
  if (!t) throw new Error(`No data for ${name} in dump`);
  return t.rows.map(r => Object.fromEntries(t.cols.map((c, i) => [c, r[i]])));
};

// Maps each dump table onto the existing Supabase table (new id is generated by the DB).
const plan = [
  { src: 'mii_financial_years', dest: 'mii_financial_years', map: (o) => ({
      label: o.label, start_date: asDate(o.start_date), end_date: asDate(o.end_date),
      created_at: ts(o.created_at), updated_at: ts(o.updated_at) }) },
  { src: 'mii_mode_of_payment', dest: 'mii_modes_of_payment', map: (o, i) => ({
      name: o.payment, display_order: i + 1, created_at: ts(o.created_at), updated_at: ts(o.updated_at) }) },
  { src: 'mii_service_types', dest: 'mii_service_types', map: (o, i) => ({
      name: o.service, display_order: i + 1, created_at: ts(o.created_at), updated_at: ts(o.updated_at) }) },
  { src: 'mii_tags', dest: 'mii_tags', map: (o) => ({
      name: o.tag_name, created_at: ts(o.created_at), updated_at: ts(o.updated_at) }) },
  { src: 'mii_clients', dest: 'mii_clients', map: (o, i, ids) => ({
      name: o.name, email: o.email, phone_number: o.phone_number == null ? null : String(o.phone_number),
      address: o.address, new_client_year: ids.mii_financial_years[o.new_client_year] ?? null,
      client_code: o.client_code, new_client: o.new_client, client_number: o.client_number,
      new_client_number: o.new_client_number, file_number: o.file_number,
      created_at: ts(o.created_at), updated_at: ts(o.updated_at) }) },
  { src: 'mii_expense', dest: 'mii_expenses', map: (o, i, ids) => ({
      sr_no: o.sr_no, expense_date: asDate(o.date), expense_name: o.expense_name, expense_amount: o.expense_amount,
      mode_of_payment_id: ids.mii_mode_of_payment[o.mode_of_payment] ?? null, service_type_id: null,
      notes: o.notes, created_at: ts(o.created_at), updated_at: ts(o.updated_at) }) },
  { src: 'mii_service_status', dest: 'mii_service_status', map: (o, i, ids) => ({
      client_id: ids.mii_clients[o.client_name] ?? null,
      service_type_id: ids.mii_service_types[o.type_of_service] ?? null,
      mode_of_payment_id: ids.mii_mode_of_payment[o.mode_of_payment] ?? null,
      fees: o.fees, received: o.received, assigned_to: o.assigned_to == null ? null : `User ${o.assigned_to}`,
      date_of_service: asDate(o.date_of_service), payment_status: !!o.payment_status, job_completed: !!o.completed,
      notes: o.notes, created_at: ts(o.created_at), updated_at: ts(o.updated_at) }) },
];

// Rows without a name are unusable in the app (NOT NULL name column), so skip them.
const nameField = { mii_mode_of_payment: 'payment', mii_service_types: 'service', mii_tags: 'tag_name' };
const prepared = plan.map(p => ({ ...p, rows: objs(p.src).filter(o => !nameField[p.src] || (o[nameField[p.src]] ?? '').toString().trim()).map((o, i) => ({ o, i })) }));

if (dry) {
  const ids = new Proxy({}, { get: () => new Proxy({}, { get: (_, k) => Number(k) }) });
  for (const p of prepared) {
    const out = p.rows.map(({ o, i }) => p.map(o, i, ids));
    console.log(`${p.dest}: ${out.length} rows`, JSON.stringify(out[out.length - 1]).slice(0, 260));
  }
  process.exit(0);
}

// Clear destination tables (children first), then insert parents first.
for (const p of [...prepared].reverse()) {
  const { error } = await supabase.from(p.dest).delete().gt('id', -1);
  if (error) { console.error(`${p.dest}: clear failed -`, error.message); process.exit(1); }
}

const ids = {}; // src table -> { oldId: newId }
for (const p of prepared) {
  ids[p.src] = {};
  const out = p.rows.map(({ o, i }) => p.map(o, i, ids));
  for (let i = 0; i < out.length; i += 500) {
    const { data, error } = await supabase.from(p.dest).insert(out.slice(i, i + 500)).select('id');
    if (error) { console.error(`${p.dest}: insert failed at row ${i} -`, error.message); process.exit(1); }
    data.forEach((r, k) => { ids[p.src][p.rows[i + k].o.id] = r.id; });
  }
  console.log(`${p.dest}: ${out.length} rows`);
}
console.log('Done');
