-- Categories, moved over from the old MySQL database (Camangal.mii_category).
--
-- Converted from the HeidiSQL dump: the MySQL session settings are dropped,
-- int AUTO_INCREMENT becomes an identity column, varchar(128) becomes text, and
-- the timestamps are read as UTC (the dump was taken with TIME_ZONE='+00:00').
-- created_by / updated_by hold the old system's user ids; there is no users
-- table here, so they are kept as plain numbers.
-- Safe to run more than once: existing ids are left alone.

create table if not exists public.mii_category (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  created_by  integer,
  updated_by  integer,
  name        text
);

insert into public.mii_category (id, created_at, updated_at, created_by, updated_by, name) values
  (61, '2025-12-09 10:14:40+00', '2025-12-09 10:14:40+00', 1, null, 'Lower TDS Certificate'),
  (62, '2025-12-09 10:14:40+00', '2025-12-09 10:14:40+00', 1, null, 'Other'),
  (63, '2025-12-09 10:14:40+00', '2025-12-09 10:14:40+00', 1, null, 'Consultancy'),
  (64, '2025-12-09 10:14:40+00', '2025-12-09 10:14:40+00', 1, null, 'FORM 26QC'),
  (65, '2025-12-09 10:14:40+00', '2025-12-09 10:14:40+00', 1, null, 'FORM 26QB'),
  (66, '2025-12-09 10:14:40+00', '2025-12-09 10:14:40+00', 1, null, 'Loan Agreement'),
  (67, '2025-12-09 10:14:40+00', '2025-12-09 10:14:40+00', 1, null, 'Scrutiny'),
  (68, '2025-12-09 10:14:40+00', '2025-12-09 10:14:40+00', 1, null, 'TDS return'),
  (69, '2025-12-09 10:14:40+00', '2025-12-09 10:14:40+00', 1, null, 'GST'),
  (70, '2025-12-09 10:14:40+00', '2025-12-09 10:14:40+00', 1, null, 'Rent'),
  (71, '2025-12-09 10:14:41+00', '2025-12-09 10:14:41+00', 1, null, 'Property Matter'),
  (72, '2025-12-09 10:14:42+00', '2025-12-09 10:14:42+00', 1, null, 'TAN'),
  (73, '2025-12-09 10:14:42+00', '2025-12-09 10:14:42+00', 1, null, 'Pan'),
  (74, '2025-12-09 10:14:43+00', '2025-12-09 10:14:43+00', 1, null, 'Property'),
  (75, '2025-12-09 10:14:44+00', '2025-12-09 10:14:44+00', 1, null, 'Valuation '),
  (76, '2025-12-09 10:14:45+00', '2025-12-09 10:14:45+00', 1, null, 'ITR'),
  (77, '2025-12-09 10:14:52+00', '2025-12-09 10:14:52+00', 1, null, 'LOAN'),
  (78, '2025-12-10 08:51:43+00', '2025-12-10 08:51:43+00', 1, null, 'Others'),
  (79, '2025-12-10 08:51:48+00', '2025-12-10 08:51:48+00', 1, null, ' Pan'),
  (80, '2025-12-12 05:16:36+00', '2025-12-12 05:16:36+00', 2, null, 'Computer (IT)'),
  (81, '2025-12-12 05:16:36+00', '2025-12-12 05:16:36+00', 2, null, 'Other Office Exp'),
  (82, '2025-12-12 05:16:36+00', '2025-12-12 05:16:36+00', 2, null, 'Office Stationery'),
  (83, '2025-12-12 05:16:36+00', '2025-12-12 05:16:36+00', 2, null, 'Misc. Exp.'),
  (84, '2025-12-12 05:16:36+00', '2025-12-12 05:16:36+00', 2, null, 'Salary'),
  (85, '2025-12-12 05:16:37+00', '2025-12-12 05:16:37+00', 2, null, 'Ad & Promotional Exp'),
  (86, '2025-12-12 05:16:37+00', '2025-12-12 05:16:37+00', 2, null, 'Website & Software'),
  (87, '2025-12-13 10:08:44+00', '2025-12-13 10:08:44+00', 2, null, '80'),
  (88, '2025-12-13 10:08:44+00', '2025-12-13 10:08:44+00', 2, null, '81'),
  (89, '2025-12-13 10:08:44+00', '2025-12-13 10:08:44+00', 2, null, '82'),
  (90, '2025-12-13 10:08:44+00', '2025-12-13 10:08:44+00', 2, null, '85'),
  (91, '2025-12-13 10:08:44+00', '2025-12-13 10:08:44+00', 2, null, '83'),
  (92, '2025-12-13 10:08:44+00', '2025-12-13 10:08:44+00', 2, null, '84'),
  (93, '2025-12-13 10:08:44+00', '2025-12-13 10:08:44+00', 2, null, '86'),
  (94, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Google Adds'),
  (95, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Computer'),
  (96, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Atul Mangal'),
  (97, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Hathway Bill'),
  (98, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'BNI Meetings'),
  (99, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'J K Paper Rim'),
  (100, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'BNI Membership Renewal'),
  (101, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Om Prakash'),
  (102, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Sikender Gupta'),
  (103, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Fesal'),
  (104, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'BNI Training'),
  (105, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'BNI Quarterly Contribution'),
  (106, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Omprakash'),
  (107, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Printer Cartraige'),
  (108, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Printer Servicing'),
  (109, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Atul Purse & Gift Bni'),
  (110, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Office Blind & Tubelight'),
  (111, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Quickheal Renewal'),
  (112, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Aquaraium'),
  (113, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Nishant Sharma'),
  (114, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Printer'),
  (115, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Bonus'),
  (116, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Atul Mobile'),
  (117, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Office'),
  (118, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Miscellaneous office'),
  (119, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Epson Scanner'),
  (120, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Sweets'),
  (121, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Busy Update'),
  (122, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Office Books - Ready Reckner (Income Tax )'),
  (123, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Truecaller'),
  (124, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Genius + GST'),
  (125, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Atul Office'),
  (126, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Atul- Jio'),
  (127, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Genius Software'),
  (128, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Hindustan Times - Newspaper'),
  (129, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'BNI'),
  (130, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Atul'),
  (131, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Taxman Licence Online'),
  (132, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Panasonic Chordless'),
  (133, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'AC Servicing'),
  (134, '2026-01-09 05:52:42+00', '2026-01-09 05:52:42+00', 2, null, 'Dinesh Sharma'),
  (135, '2026-01-15 08:12:30+00', '2026-01-15 08:12:30+00', 2, null, 'Personal Exp.')
on conflict (id) do nothing;

-- Explicit ids don't move the identity sequence; continue after the highest one
-- (MySQL had AUTO_INCREMENT=136)
select setval(pg_get_serial_sequence('public.mii_category', 'id'), greatest((select max(id) from public.mii_category), 135));

-- Same access as the other tables: signed-in users only
alter table public.mii_category enable row level security;
drop policy if exists "authenticated full access" on public.mii_category;
create policy "authenticated full access" on public.mii_category for all to authenticated using (true) with check (true);
grant select, insert, update, delete on public.mii_category to authenticated;

-- Make the API see the new table straight away
notify pgrst, 'reload schema';
