-- Baseline schema for the app tables.
--
-- Reconstructed from how the app (src/lib/tables.js) and the import script
-- (scripts/seed.mjs) use each column; the live tables were created by hand in the
-- dashboard. Every statement is "if not exists", so running this against the
-- existing project changes nothing. Compare with the live database before relying
-- on it for a new one (e.g. `supabase db diff` after linking the project).

-- Masters -------------------------------------------------------------------

create table if not exists public.mii_financial_years (
  id          bigint generated by default as identity primary key,
  label       text not null,               -- e.g. "2026-27"; client codes use it as their prefix
  start_date  date,
  end_date    date,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.mii_modes_of_payment (
  id             bigint generated by default as identity primary key,
  name           text not null,
  display_order  integer,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists public.mii_service_types (
  id             bigint generated by default as identity primary key,
  name           text not null,
  display_order  integer,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists public.mii_tags (
  id          bigint generated by default as identity primary key,
  name        text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Clients -------------------------------------------------------------------

create table if not exists public.mii_clients (
  id                 bigint generated by default as identity primary key,
  name               text,                 -- required by the app form; nullable so legacy imports load
  file_number        text,
  email              text,
  phone_number       text,
  address            text,
  new_client         smallint default 0,   -- 1 = New Client, 0 = Old Client
  new_client_year    bigint references public.mii_financial_years (id) on delete set null,
  new_client_number  text,                 -- "N001", "N002", ... for new clients
  client_number      text,                 -- legacy column filled by the import, unused by the app
  client_code        text,                 -- year prefix + 6-digit sequence, e.g. "2627000123"
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

-- Transactions ----------------------------------------------------------------

create table if not exists public.mii_expenses (
  id                  bigint generated by default as identity primary key,
  sr_no               text,
  expense_date        date,
  expense_name        text not null,
  expense_amount      numeric(14, 2) not null default 0,
  mode_of_payment_id  bigint references public.mii_modes_of_payment (id) on delete set null,
  service_type_id     bigint references public.mii_service_types (id) on delete set null,
  notes               text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create table if not exists public.mii_service_status (
  id                  bigint generated by default as identity primary key,
  -- restrict: a client with billing history can't be deleted out from under it
  client_id           bigint references public.mii_clients (id) on delete restrict,
  service_type_id     bigint references public.mii_service_types (id) on delete set null,
  mode_of_payment_id  bigint references public.mii_modes_of_payment (id) on delete set null,
  tag_id              bigint references public.mii_tags (id) on delete set null,
  fees                numeric(14, 2),
  received            numeric(14, 2),
  assigned_to         text,
  date_of_service     date,
  remarks             text,
  payment_status      boolean not null default false,
  job_completed       boolean not null default false,
  notes               text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- Foreign-key indexes (lookups and deletes on the referenced tables) ---------------

create index if not exists mii_clients_new_client_year_idx        on public.mii_clients (new_client_year);
create index if not exists mii_expenses_mode_of_payment_id_idx     on public.mii_expenses (mode_of_payment_id);
create index if not exists mii_expenses_service_type_id_idx        on public.mii_expenses (service_type_id);
create index if not exists mii_service_status_client_id_idx        on public.mii_service_status (client_id);
create index if not exists mii_service_status_service_type_id_idx  on public.mii_service_status (service_type_id);
create index if not exists mii_service_status_mode_of_payment_idx  on public.mii_service_status (mode_of_payment_id);
create index if not exists mii_service_status_tag_id_idx           on public.mii_service_status (tag_id);
